In [1]:
import pandas as pd
import requests
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Create a reference the CSV four-digit-pin-codes-and-frequency.csv
pins_csv_path = "raw_data/four-digit-pin-codes-and-frequency.csv"
pins_df = pd.read_csv(pins_csv_path)

# pins_df=pd.read_csv("four-digit-pin-codes-and-frequency.csv")
pins_df.head(20)

        Pins
0   1234;255
1   1111;244
2   0000;221
3   1212;212
4   7777;203
5   1004;199
6   2000;199
7   4444;196
8   2222;195
9   6969;195
10  9999;192
11  3333;191
12  5555;190
13  6666;190
14  1122;188
15  1313;185
16  8888;185
17  2001;184
18  4321;184
19  1010;183

In [3]:
# Split column Pins in two columns: pins and frequency.
new_pins_df = pd.DataFrame(pins_df.Pins.str.split(';',1).tolist(), columns = ["pins","frequency"])
new_pins_df.dtypes

pins         object
frequency    object
dtype: object

In [4]:
# Change object dtypes to numeric
new_pins_df = new_pins_df.apply(pd.to_numeric, errors='coerce')
new_pins_df.dtypes

pins         int64
frequency    int64
dtype: object

In [5]:
# Total of unique frequency numbers = 150
# frequency_list_df =new_pins_df.drop_duplicates(subset=["frequency"],keep="first")
# count_frequency = frequency_list_df.frequency.count()
# print(count_frequency)

150

In [6]:
list=new_pins_df.frequency.unique()
num_elements_list=len(list)
print(list, num_elements_list)

[255 244 221 212 203 199 196 195 192 191 190 188 185 184 183 181 180 179
 178 177 175 174 173 172 171 170 169 168 167 166 165 164 163 162 161 160
 159 158 157 156 155 154 153 152 151 150 149 148 147 146 145 144 143 142
 141 140 139 138 137 136 135 134 133 132 131 130 129 128 127 126 125 124
 123 122 121 120 119 118 117 116 115 114 113 112 111 110 109 108 107 106
 105 104 103 102 101 100  99  98  97  96  95  94  93  92  91  90  89  88
  87  86  85  84  83  82  81  80  79  78  77  76  75  74  73  72  71  70
  69  68  67  66  65  64  63  62  61  60  59  58  57  55  54  53  51  50
  48  46  44  42  36   0] 150

In [7]:
#Create bins
bins=[-1, 97, 148, 255]
bin_labels=["difficult","moderate","easy"]
new_pins_df["level"]=pd.cut(new_pins_df["frequency"], bins, labels= bin_labels)
new_pins_df.to_csv("raw_data/pin-frequency-level.csv", index= False)

In [8]:
new_pins_df

      pins  frequency      level
0     1234        255       easy
1     1111        244       easy
2        0        221       easy
3     1212        212       easy
4     7777        203       easy
5     1004        199       easy
6     2000        199       easy
7     4444        196       easy
8     2222        195       easy
9     6969        195       easy
10    9999        192       easy
11    3333        191       easy
12    5555        190       easy
13    6666        190       easy
14    1122        188       easy
15    1313        185       easy
16    8888        185       easy
17    2001        184       easy
18    4321        184       easy
19    1010        183       easy
20     909        181       easy
21    2580        180       easy
22       7        179       easy
23    1818        178       easy
24    1230        177       easy
25    1984        175       easy
26    1986        175       easy
27      70        174       easy
28    1985        174       easy
29     987        173       easy
...    ...        ...        ...
9970  8397         57  difficult
9971  8539         57  difficult
9972  8646         57  difficult
9973  9695         57  difficult
9974  9805         57  difficult
9975  6806         55  difficult
9976  7993         55  difficult
9977  8146         55  difficult
9978  8343         55  difficult
9979  8557         55  difficult
9980   439         54  difficult
9981  8438         54  difficult
9982  9047         54  difficult
9983  9539         54  difficult
9984  6093         53  difficult
9985  7063         53  difficult
9986  8196         53  difficult
9987  6827         51  difficult
9988  7394         51  difficult
9989   859         50  difficult
9990  8957         48  difficult
9991  9480         48  difficult
9992  6793         46  difficult
9993   738         44  difficult
9994  8398         44  difficult
9995  6835         42  difficult
9996  7637         42  difficult
9997  9629         42  difficult
9998  8093         36  difficult
9999  8068          0  difficult

[10000 rows x 3 columns]

In [9]:
new_pins_df.groupby(by="level").size()

level
difficult    5867
moderate     3953
easy          180
dtype: int64

In [10]:
def map_level(pdf):
    data_url = 'https://ucbe-mastermind.herokuapp.com/data'
    response = requests.get(data_url)

    data_df = pd.DataFrame(response.json())
    result_data = pd.merge(data_df, pdf, how="left", left_on='password', right_on='pins')
    return(result_data)

In [11]:
output_data=map_level(new_pins_df)

In [12]:
output_data

,game,guess,guess_number,password,player,record_id,right_digit,right_place,pins,frequency,level
0,1,1234,1,238,player3793,1,0,2,238,93,difficult
1,1,1256,2,238,player3793,2,0,1,238,93,difficult
2,1,1738,3,238,player3793,3,0,2,238,93,difficult
3,1,1039,4,238,player3793,4,1,1,238,93,difficult
4,1,1794,5,238,player3793,5,0,0,238,93,difficult
5,1,230,6,238,player3793,6,0,3,238,93,difficult
6,1,238,7,238,player3793,7,0,4,238,93,difficult
7,2,1234,1,7201,theBest,8,1,1,7201,97,difficult
8,2,1567,2,7201,theBest,9,2,0,7201,97,difficult
9,2,289,3,7201,theBest,10,1,1,7201,97,difficult
10,2,5298,4,7201,theBest,11,0,1,7201,97,difficult
11,2,6210,5,7201,theBest,12,2,1,7201,97,difficult
12,2,7201,6,7201,theBest,13,0,4,7201,97,difficult
13,3,1234,1,4261,theBest,14,2,1,4261,86,difficult
14,3,1325,2,4261,theBest,15,2,0,4261,86,difficult
15,3,3246,3,4261,theBest,16,2,1,4261,86,difficult
16,3,4237,4,4261,theBest,17,0,2,4261,86,difficult
17,3,4261,5,4261,theBest,18,0,4,4261,86,difficult
18,4,5555,1,3960,Tamarind,19,0,0,3960,101,moderate
19,4,1111,2,3960,Tamarind,20,0,0,3960,101,moderate
20,4,2222,3,3960,Tamarind,21,0,0,3960,101,moderate
21,4,3333,4,3960,Tamarind,22,0,1,3960,101,moderate
22,4,4444,5,3960,Tamarind,23,0,0,3960,101,moderate
23,4,6666,6,3960,Tamarind,24,0,1,3960,101,moderate
24,4,7777,7,3960,Tamarind,25,0,0,3960,101,moderate
25,4,8888,8,3960,Tamarind,26,0,0,3960,101,moderate
26,4,9999,9,3960,Tamarind,27,0,1,3960,101,moderate
27,4,0,10,3960,Tamarind,28,0,1,3960,101,moderate
28,4,3222,11,3960,Tamarind,29,0,1,3960,101,moderate
29,4,3622,12,3960,Tamarind,30,1,1,3960,101,moderate
...,...,...,...,...,...,...,...,...,...,...,...
481,52,1234,8,2175,name_1,482,2,0,2175,102,moderate
482,52,1234,9,2175,name_1,483,2,0,2175,102,moderate
483,52,1234,10,2175,name_1,484,2,0,2175,102,moderate
484,52,1234,11,2175,name_1,485,2,0,2175,102,moderate
485,52,1234,12,2175,name_1,486,2,0,2175,102,moderate
486,52,1234,13,2175,name_1,487,2,0,2175,102,moderate
487,52,1234,14,2175,name_1,488,2,0,2175,102,moderate
488,52,1234,15,2175,name_1,489,2,0,2175,102,moderate
489,52,1234,16,2175,name_1,490,2,0,2175,102,moderate
490,52,1234,17,2175,name_1,491,2,0,2175,102,moderate
491,52,1234,18,2175,name_1,492,2,0,2175,102,moderate
492,52,1234,19,2175,name_1,493,2,0,2175,102,moderate
493,52,1234,20,2175,name_1,494,2,0,2175,102,moderate
494,52,1234,21,2175,name_1,495,2,0,2175,102,moderate
495,52,1234,22,2175,name_1,496,2,0,2175,102,moderate
496,52,1234,23,2175,name_1,497,2,0,2175,102,moderate
497,52,1234,24,2175,name_1,498,2,0,2175,102,moderate
498,52,1234,25,2175,name_1,499,2,0,2175,102,moderate
499,53,7543,1,6181,Andrea,500,0,0,6181,88,difficult
500,53,1034,2,6181,Andrea,501,1,0,6181,88,difficult
501,53,8111,3,6181,Andrea,502,1,2,6181,88,difficult
502,53,8181,4,6181,Andrea,503,0,3,6181,88,difficult
503,53,8180,5,6181,Andrea,504,0,2,6181,88,difficult
504,53,5181,6,6181,Andrea,505,0,3,6181,88,difficult
505,53,1181,7,6181,Andrea,506,0,3,6181,88,difficult
506,53,2181,8,6181,Andrea,507,0,3,6181,88,difficult
507,53,181,9,6181,Andrea,508,0,3,6181,88,difficult
508,53,7181,10,6181,Andrea,509,0,3,6181,88,difficult
509,53,9181,11,6181,Andrea,510,0,3,6181,88,difficult
510,53,6181,12,6181,Andrea,511,0,4,6181,88,difficult